CMAKE_MINIMUM_REQUIRED(VERSION 3.10)
PROJECT(Tests)

LOAD_AI_CORE()
LOAD_OPENCV()

IF(TARGET_OS STREQUAL "Android")
    LOAD_ANDROID_ENV()
    LIST(APPEND ANDROID_JIN_LIBS mediandk)
ENDIF()

SET(DEPENDENCY_INCLUDES
    ${OpenCV_INCLUDE_DIRS}
    ${CMAKE_CURRENT_SOURCE_DIR}/../src
    ${CMAKE_CURRENT_SOURCE_DIR}/../examples
    ${PROJECT_INCLUDE_DIR}
)

SET(DEPENDENCY_LIBS
    ai_pipe::ai_pipe_examples
    ai_pipe::ai_pipe
    ai_core::ai_core
    logger::logger
    GTest::gtest
    GTest::gtest_main
    ${OpenCV_LIBS}
    ${ANDROID_JIN_LIBS}
)

FILE(GLOB CURRENT_DIR_SRCS ${CMAKE_CURRENT_SOURCE_DIR}/*.cpp ${CMAKE_CURRENT_SOURCE_DIR}/*.cc)

MESSAGE(STATUS "APP SOURCES: ${CURRENT_DIR_SRCS}")

FILE(MAKE_DIRECTORY ${PROJECT_OUTPUT_DIR}/bin/tests)
SET(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${PROJECT_OUTPUT_DIR}/bin/tests)

ADD_EXECUTABLE(ai_pipe_tests ${CURRENT_DIR_SRCS})

TARGET_INCLUDE_DIRECTORIES(ai_pipe_tests PRIVATE ${DEPENDENCY_INCLUDES})

TARGET_LINK_LIBRARIES(ai_pipe_tests PRIVATE ${DEPENDENCY_LIBS})

INSTALL(TARGETS ai_pipe_tests DESTINATION tests)
