CMAKE_MINIMUM_REQUIRED(VERSION 3.16)

AI_PIPE_EXTRACT_VERSION()
PROJECT(AIPipeExamples VERSION ${AI_PIPE_VERSION})

SET(CMAKE_POSITION_INDEPENDENT_CODE ON)

LOAD_OPENCV()
LOAD_AI_CORE()

FILE(GLOB_RECURSE CURRENT_DIR_SRCS 
		${CMAKE_CURRENT_SOURCE_DIR}/*.cpp 
		${CMAKE_CURRENT_SOURCE_DIR}/nodes/*.cpp 
		${CMAKE_CURRENT_SOURCE_DIR}/tracker/*.cpp 
)

SET(DEPENDENCY_INCLUDES
	${PROJECT_INCLUDE_DIR}
	${OpenCV_INCLUDE_DIRS}
)

SET(DEPENDENCY_LIBS
	ai_pipe::ai_pipe
	ai_core::ai_core
	logger::logger
	${OpenCV_LIBS}
)

# Build Shared Library
ADD_LIBRARY(ai_pipe_examples SHARED ${CURRENT_DIR_SRCS})


ADD_LIBRARY(ai_pipe::ai_pipe_examples ALIAS ai_pipe_examples)

TARGET_INCLUDE_DIRECTORIES(ai_pipe_examples 
	PRIVATE
		$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}>
		${DEPENDENCY_INCLUDES}
)

TARGET_LINK_LIBRARIES(ai_pipe_examples PRIVATE ${DEPENDENCY_LIBS})

INSTALL(TARGETS ai_pipe_examples
    EXPORT ai_export_set
    LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR} COMPONENT lib
    ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR} COMPONENT lib
    RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR} COMPONENT bin
)
