CMAKE_MINIMUM_REQUIRED(VERSION 3.10)

PROJECT(ai_sdk VERSION 1.0.0)

SET(CMAKE_POSITION_INDEPENDENT_CODE ON)

LOAD_OPENCV()
LOAD_LOGGER()
LOAD_COMMON_UTILS()

IF (TARGET_OS STREQUAL "Android")
    LOAD_ANDROID_ENV()
ENDIF()

SET(DEPENDENCY_INCLUDES
	${OpenCV_INCLUDE_DIRS} 
)

SET(DEPENDENCY_LIBS
	ai_pipe::ai_pipe
	logger::logger
    common_utils::common_utils
	${OpenCV_LIBS}
	${ANDROID_JIN_LIBS}
)

# Public headers
FILE(GLOB_RECURSE CURRENT_DIR_PUBLIC_HEAD 
	${CMAKE_CURRENT_SOURCE_DIR}/api/*.hpp 
	${CMAKE_CURRENT_SOURCE_DIR}/api/*.h
) 

FILE(GLOB CURRENT_DIR_PRIVATE_HEAD 
	${CMAKE_CURRENT_SOURCE_DIR}/*.hpp
)

FILE(GLOB_RECURSE CURRENT_DIR_SRCS 
	${CMAKE_CURRENT_SOURCE_DIR}/*.cpp 
	${CMAKE_CURRENT_SOURCE_DIR}/*.cc
)

# Build Shared Library
ADD_LIBRARY(ai_sdk SHARED ${CURRENT_DIR_SRCS})

ADD_LIBRARY(ai_sdk::ai_sdk ALIAS ai_sdk)

TARGET_COMPILE_DEFINITIONS(ai_sdk PRIVATE AI_WORKFLOW_BUILD_DLL)

TARGET_INCLUDE_DIRECTORIES(ai_sdk
	PUBLIC
		$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}>
		$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/api>
		$<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}>
	PRIVATE
		${DEPENDENCY_INCLUDES}
)

TARGET_LINK_LIBRARIES(ai_sdk PRIVATE ${DEPENDENCY_LIBS})

INSTALL(TARGETS ai_sdk
    EXPORT ai_export_export_set
    LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR} COMPONENT lib
    ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR} COMPONENT lib
    RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR} COMPONENT bin
)

INSTALL(FILES ${CURRENT_DIR_PUBLIC_HEAD}
    DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/ai_sdk
    COMPONENT dev
)

INCLUDE(CMakePackageConfigHelpers)
# Generate the ai_sdk-config.cmake and ai_sdk-config-version.cmake files
WRITE_BASIC_PACKAGE_VERSION_FILE(
    "${CMAKE_CURRENT_BINARY_DIR}/ai_sdk-config-version.cmake"
    VERSION ${PROJECT_VERSION}
    COMPATIBILITY AnyNewerVersion
)

EXPORT(EXPORT ai_export_export_set
    FILE "${CMAKE_CURRENT_BINARY_DIR}/ai_sdk-targets.cmake"
    NAMESPACE ai_sdk::
)

CONFIGURE_FILE(
    "${CMAKE_SOURCE_DIR}/cmake/ai_sdk-config.cmake.in"
    "${CMAKE_CURRENT_BINARY_DIR}/ai_sdk-config.cmake"
    @ONLY
)

INSTALL(FILES
    "${CMAKE_CURRENT_BINARY_DIR}/ai_sdk-config.cmake"
    "${CMAKE_CURRENT_BINARY_DIR}/ai_sdk-config-version.cmake"
    DESTINATION ${CMAKE_INSTALL_DATADIR}
    COMPONENT dev
)

INSTALL(EXPORT ai_export_export_set
    FILE ai_sdk-targets.cmake
    NAMESPACE ai_sdk::
    DESTINATION ${CMAKE_INSTALL_DATADIR}
	COMPONENT dev
)
