CMAKE_MINIMUM_REQUIRED(VERSION 3.16)

AI_PIPE_EXTRACT_VERSION()
PROJECT(AIPipeSrc VERSION ${AI_PIPE_VERSION})

SET(CMAKE_POSITION_INDEPENDENT_CODE ON)

LOAD_LOGGER()

# Public headers
FILE(GLOB_RECURSE CURRENT_DIR_PUBLIC_HEAD ${CMAKE_CURRENT_SOURCE_DIR}/api/*.hpp) 

FILE(GLOB_RECURSE CURRENT_DIR_HEAD 
	${CMAKE_CURRENT_SOURCE_DIR}/*.hpp
)

FILE(GLOB_RECURSE CURRENT_DIR_SRCS 
		${CMAKE_CURRENT_SOURCE_DIR}/*.cpp 
)

SET(DEPENDENCY_INCLUDES
	${PROJECT_INCLUDE_DIR}
	${PROJECT_INCLUDE_DIR}/ai_pipe
)

SET(DEPENDENCY_LIBS
	logger::logger
)

# Build Shared Library
ADD_LIBRARY(ai_pipe ${CURRENT_DIR_SRCS})

ADD_LIBRARY(ai_pipe::ai_pipe ALIAS ai_pipe)

TARGET_INCLUDE_DIRECTORIES(ai_pipe 
	PUBLIC
		$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/api>	
		$<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}>
	PRIVATE 
		$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}>
		$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/api>
		$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/api/ai_pipe>
		${DEPENDENCY_INCLUDES}
)

TARGET_LINK_LIBRARIES(ai_pipe PRIVATE ${DEPENDENCY_LIBS})

# Generate the ai_pipe-config.cmake and ai_pipe-config-version.cmake files
WRITE_BASIC_PACKAGE_VERSION_FILE(
    "${CMAKE_CURRENT_BINARY_DIR}/ai_pipe-config-version.cmake"
    VERSION ${PROJECT_VERSION}
    COMPATIBILITY AnyNewerVersion
)

CONFIGURE_FILE(
    "${CMAKE_SOURCE_DIR}/cmake/ai_pipe-config.cmake.in"
    "${CMAKE_CURRENT_BINARY_DIR}/ai_pipe-config.cmake"
    @ONLY
)

INSTALL(FILES ${CURRENT_DIR_PUBLIC_HEAD}
    DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/ai_pipe
    COMPONENT dev
)

INSTALL(TARGETS ai_pipe
    EXPORT ai_export_set
    LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR} COMPONENT lib
    ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR} COMPONENT lib
    RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR} COMPONENT bin
)

INSTALL(FILES ${CURRENT_DIR_PUBLIC_HEAD}
    DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/ai_pipe
    COMPONENT dev
)

INSTALL(FILES
    "${CMAKE_CURRENT_BINARY_DIR}/ai_pipe-config.cmake"
    "${CMAKE_CURRENT_BINARY_DIR}/ai_pipe-config-version.cmake"
    DESTINATION ${CMAKE_INSTALL_DATADIR}
    COMPONENT dev
)

INSTALL(EXPORT ai_export_set
    FILE ai_pipe-targets.cmake
    NAMESPACE ai_pipe::
    DESTINATION ${CMAKE_INSTALL_DATADIR}
	COMPONENT dev
)

EXPORT(EXPORT ai_export_set
    FILE "${CMAKE_CURRENT_BINARY_DIR}/ai_pipe-targets.cmake"
    NAMESPACE ai_pipe::
)
