CMAKE_MINIMUM_REQUIRED(VERSION 3.10)
PROJECT(Benchmarks)

SET(DEPENDENCY_INCLUDES
    ${OpenCV_INCLUDE_DIRS}
    ${PROJECT_INCLUDE_DIR}
)

SET(DEPENDENCY_LIBS
    logger::logger
    benchmark::benchmark 
)

FILE(GLOB CURRENT_DIR_SRCS ${CMAKE_CURRENT_SOURCE_DIR}/*.cpp ${CMAKE_CURRENT_SOURCE_DIR}/*.cc)

MESSAGE(STATUS "Benchmark SOURCES: ${CURRENT_DIR_SRCS}")

FILE(MAKE_DIRECTORY ${PROJECT_OUTPUT_DIR}/bin/benchmarks)
SET(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${PROJECT_OUTPUT_DIR}/bin/benchmarks)

ADD_EXECUTABLE(ai_pipe_benchmarks ${CURRENT_DIR_SRCS})
TARGET_INCLUDE_DIRECTORIES(ai_pipe_benchmarks PRIVATE ${DEPENDENCY_INCLUDES})
TARGET_LINK_LIBRARIES(ai_pipe_benchmarks PRIVATE ${DEPENDENCY_LIBS})
INSTALL(TARGETS ai_pipe_benchmarks DESTINATION benchmarks)
