# .github/workflows/main.yml

name: CMake CI for Linux GCC with dependencies

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-24.04

    env:
      CC: gcc-13
      CXX: g++-13

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
          lfs: true

    - name: Install GCC 13 and FFmpeg
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-13 g++-13
        sudo apt-get install libavcodec-dev libavformat-dev libavutil-dev libswscale-dev libdc1394-dev

    - name: Download and extract dependencies
      run: |
        DEST_DIR="${{ github.workspace }}/3rdparty/target/"
        OUTPUT_FILE="dependency.tgz"
        
        RELEASE_URL="https://github.com/sinterwong/ai-pipe/releases/download/v0.2.3-alpha/dependency_Linux_x86_64.tgz"
        
        mkdir -p "$DEST_DIR"
        
        echo "Downloading dependencies from GitHub Releases..."
        curl -L "${RELEASE_URL}" -o "${OUTPUT_FILE}"
        
        echo "Extracting dependencies..."
        tar -xzf "${OUTPUT_FILE}" -C "$DEST_DIR"
        
        echo "Dependencies installed."

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
        echo "install-dir=${{ github.workspace }}/install" >> "$GITHUB_OUTPUT"
    
    - name: Set up test env
      run: |
        echo "LD_LIBRARY_PATH=${{ github.workspace }}/install/lib:\
        ${{ github.workspace }}/3rdparty/target/Linux_x86_64/dependency_lib:\
        ${{ github.workspace }}/3rdparty/target/Linux_x86_64/logger/lib:\
        ${{ github.workspace }}/3rdparty/target/Linux_x86_64/gtest/lib:\
        ${{ github.workspace }}/3rdparty/target/Linux_x86_64/opencv/lib:\
        ${{ github.workspace }}/3rdparty/target/Linux_x86_64/ai_core/lib:\
        ${{ github.workspace }}/install/lib:\
        $LD_LIBRARY_PATH" >> $GITHUB_ENV

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_INSTALL_PREFIX=${{ steps.strings.outputs.install-dir }}
        -DCMAKE_BUILD_TYPE=Release
        -DBUILD_AI_PIPE_TESTS=ON
        -DBUILD_AI_PIPE_EXAMPLES=ON
        -DBUILD_AI_PIPE_BENCHMARKS=ON
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config Release

    - name: Install project
      run: cmake --install ${{ steps.strings.outputs.build-output-dir }}

    - name: Run GTests
      working-directory: ${{ steps.strings.outputs.install-dir }}
      run: ./tests/ai_pipe_tests --gtest_filter=*.*
